import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { validateFontSource } from '../src/font-validate';
import source from '../src/font.json';
import { renderTextToSVG } from '../src/svg-export';

const { config, chars } = validateFontSource(source);

test('renders strokes and reports missing glyphs', () => {
  const { svg, missing } = renderTextToSVG(chars, 'Hi é', { weight: config.weight });
  assert.match(svg, /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg"/);
  assert.match(svg, /<path d="M /);
  assert.match(svg, /stroke-width="2"/);
  assert.deepEqual(missing, ['é']);
});

test('background paints a rect over the whole viewBox', () => {
  const { svg } = renderTextToSVG(chars, 'A', { background: '#111' });
  const view = /viewBox="([-\d.]+) ([-\d.]+) ([-\d.]+) ([-\d.]+)"/.exec(svg);
  assert.ok(view);
  const rect = /<rect x="([-\d.]+)" y="([-\d.]+)" width="([-\d.]+)" height="([-\d.]+)" fill="#111"/.exec(
    svg
  );
  assert.ok(rect);
  assert.deepEqual(rect.slice(1), view.slice(1));
});

test('width scales the rendered size but not the viewBox', () => {
  const plain = renderTextToSVG(chars, 'A').svg;
  const scaled = renderTextToSVG(chars, 'A', { width: 800 }).svg;

  const viewBox = (svg: string) => /viewBox="([^"]+)"/.exec(svg)?.[1];
  assert.equal(viewBox(scaled), viewBox(plain));
  assert.match(scaled, /width="800"/);
});

test('no background means no rect at all', () => {
  assert.doesNotMatch(renderTextToSVG(chars, 'A').svg, /<rect/);
});

test('monospace and proportional layouts differ', () => {
  const mono = renderTextToSVG(chars, 'il', { monospace: true }).svg;
  const proportional = renderTextToSVG(chars, 'il', { monospace: false }).svg;
  assert.notEqual(mono, proportional);
});

// The committed banner is generated by scripts/update-cover.ts; regenerating it
// here proves the renderer still produces the same output.
test('reproduces public/brutalita-cover.svg', () => {
  const text = [
    config.name,
    '',
    'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQ',
    'qRrSsTtUuVvWwXxYyZz0123456789!"#$',
    "%&'()*+,-./:;<=>?@[\\]^_`{|}~´",
    '',
    '',
    'Brutalita is an experimental font and editor.',
    'Create and download your own font.',
  ].join('\n');

  const { svg } = renderTextToSVG(chars, text, {
    weight: config.weight,
    monospace: config.monospace,
    color: '#fff',
    padding: 72,
    background: '#111',
    width: 800,
  });

  assert.equal(svg, readFileSync('public/brutalita-cover.svg', 'utf8'));
});
